// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ApolloProvider = require("reason-apollo/src/ApolloProvider.bs.js");
var Client$ReactTemplate = require("./Client.bs.js");
var UserEmail$ReactTemplate = require("./UserEmail.bs.js");
var OpenIssues$ReactTemplate = require("./OpenIssues.bs.js");
var UserRepositories$ReactTemplate = require("./UserRepositories.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ApolloProvider.make(Client$ReactTemplate.instance, /* array */[ReasonReact.element(/* None */0, /* None */0, UserEmail$ReactTemplate.make(/* array */[]))])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ApolloProvider.make(Client$ReactTemplate.instance, /* array */[ReasonReact.element(/* None */0, /* None */0, UserRepositories$ReactTemplate.make(/* array */[]))])), "index2");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ApolloProvider.make(Client$ReactTemplate.instance, /* array */[ReasonReact.element(/* None */0, /* None */0, OpenIssues$ReactTemplate.make(/* array */[]))])), "index3");

/*  Not a pure module */
