// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_json = require("bs-platform/lib/js/js_json.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Graphql_error = Caml_exceptions.create("OpenIssues-ReactTemplate.GetIssues.Graphql_error");

var query = "query   {\nrepository(owner: \"facebook\", name: \"reason\")  {\nid  \nissues(orderBy: {field: UPDATED_AT, direction: DESC}, first: 10)  {\nnodes  {\nid  \ntitle  \n}\n}\n}\n}";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match) {
    var value$1 = match[0]["repository"];
    var match$1 = Js_json.decodeNull(value$1);
    var tmp;
    if (match$1) {
      tmp = /* None */0;
    } else {
      var match$2 = Js_json.decodeObject(value$1);
      var tmp$1;
      if (match$2) {
        var value$2 = match$2[0];
        var value$3 = value$2["id"];
        var match$3 = Js_json.decodeString(value$3);
        var tmp$2;
        if (match$3) {
          tmp$2 = match$3[0];
        } else {
          throw Graphql_error;
        }
        var value$4 = value$2["issues"];
        var match$4 = Js_json.decodeObject(value$4);
        var tmp$3;
        if (match$4) {
          var value$5 = match$4[0]["nodes"];
          var match$5 = Js_json.decodeNull(value$5);
          var tmp$4;
          if (match$5) {
            tmp$4 = /* None */0;
          } else {
            var match$6 = Js_json.decodeArray(value$5);
            var tmp$5;
            if (match$6) {
              tmp$5 = match$6[0].map((function (value) {
                      var match = Js_json.decodeNull(value);
                      if (match) {
                        return /* None */0;
                      } else {
                        var match$1 = Js_json.decodeObject(value);
                        var tmp;
                        if (match$1) {
                          var value$1 = match$1[0];
                          var value$2 = value$1["id"];
                          var match$2 = Js_json.decodeString(value$2);
                          var tmp$1;
                          if (match$2) {
                            tmp$1 = match$2[0];
                          } else {
                            throw Graphql_error;
                          }
                          var value$3 = value$1["title"];
                          var match$3 = Js_json.decodeString(value$3);
                          var tmp$2;
                          if (match$3) {
                            tmp$2 = match$3[0];
                          } else {
                            throw Graphql_error;
                          }
                          tmp = {
                            id: tmp$1,
                            title: tmp$2
                          };
                        } else {
                          throw Graphql_error;
                        }
                        return /* Some */[tmp];
                      }
                    }));
            } else {
              throw Graphql_error;
            }
            tmp$4 = /* Some */[tmp$5];
          }
          tmp$3 = {
            nodes: tmp$4
          };
        } else {
          throw Graphql_error;
        }
        tmp$1 = {
          id: tmp$2,
          issues: tmp$3
        };
      } else {
        throw Graphql_error;
      }
      tmp = /* Some */[tmp$1];
    }
    return {
            repository: tmp
          };
  } else {
    throw Graphql_error;
  }
}

function make() {
  return {
          query: query,
          variables: null,
          parse: parse
        };
}

function makeWithVariables() {
  return {
          query: query,
          variables: null,
          parse: parse
        };
}

function ret_type() {
  return /* module */[];
}

var MT_Ret = /* module */[];

var GetIssues = /* module */[
  /* Graphql_error */Graphql_error,
  /* query */query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var GetIssuesQuery = ReasonApollo.CreateQuery([
      query,
      parse
    ]);

var component = ReasonReact.statelessComponent("Page");

function make$1() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var issuesQuery = make(/* () */0);
              return ReasonReact.element(/* None */0, /* None */0, Curry.app(GetIssuesQuery[/* make */3], [
                              /* Some */[issuesQuery.variables],
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              (function (param) {
                                  var result = param[/* result */0];
                                  if (typeof result === "number") {
                                    if (result === 0) {
                                      return React.createElement("div", undefined, "Loading");
                                    } else {
                                      return React.createElement("div", undefined, "No Data");
                                    }
                                  } else if (result.tag) {
                                    var match = result[0].repository;
                                    var tmp;
                                    if (match) {
                                      var match$1 = match[0].issues.nodes;
                                      tmp = match$1 ? $$Array.map((function (node) {
                                                if (node) {
                                                  var node$1 = node[0];
                                                  return React.createElement("li", {
                                                              key: node$1.id
                                                            }, node$1.title);
                                                } else {
                                                  return "None";
                                                }
                                              }), match$1[0]) : "None";
                                    } else {
                                      tmp = "None";
                                    }
                                    return React.createElement("ul", undefined, tmp);
                                  } else {
                                    console.log(result[0]);
                                    return React.createElement("div", undefined, null);
                                  }
                                })
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.GetIssues = GetIssues;
exports.GetIssuesQuery = GetIssuesQuery;
exports.component = component;
exports.make = make$1;
/* GetIssuesQuery Not a pure module */
