// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function $pipe$unknown$great(fn, opt) {
  if (opt) {
    return Curry._1(fn, opt[0]);
  } else {
    return /* None */0;
  }
}

function $pipe$unknown$great$great(fn, opt) {
  if (opt) {
    return /* Some */[Curry._1(fn, opt[0])];
  } else {
    return /* None */0;
  }
}

function $pipe$unknown(opt, $$default) {
  if (opt) {
    return opt[0];
  } else {
    return $$default;
  }
}

exports.$pipe$unknown$great = $pipe$unknown$great;
exports.$pipe$unknown$great$great = $pipe$unknown$great$great;
exports.$pipe$unknown = $pipe$unknown;
/* No side effect */
